# Build settings
markdown: kramdown
theme: minima

lsi: false
safe: true
source: https://github.com/crichgriffin/crichgriffin.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
